name: Spring CI

on:
  pull_request:
    branches: 
      - develop 
    paths:
      - 'BACK/spring-app/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Set application-test.properties
      run: |
        mkdir -p BACK/spring-app/src/main/resources
        cat <<EOF > BACK/spring-app/src/main/resources/application-test.properties
        ${{ secrets.APPLICATION_PROPERTIES_FOR_TEST }}
        EOF
        
    - name: Build with Gradle
      run: |
        cd BACK/spring-app/
        chmod +x ./gradlew
        ./gradlew build
